# Generated by Django 2.2.1 on 2019-06-01 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='权限名称')),
                ('url', models.CharField(max_length=255, verbose_name='URL名称')),
                ('per_method', models.SmallIntegerField(choices=[(1, 'GET'), (2, 'POST')], default=1, verbose_name='请求方法')),
                ('argument_list', models.CharField(blank=True, help_text='多个参数之间用英文半角逗号隔开', max_length=255, null=True, verbose_name='参数列表')),
                ('describe', models.CharField(max_length=255, verbose_name='描述')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
                'permissions': (('views_user_list', '查看人员信息表'), ('views_user_info', '查看人员详细信息')),
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torch.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'torch人员权限映射表',
                'verbose_name_plural': 'torch人员权限映射表',
                'permissions': (('views_user_permission_list', '查看人员权限信息表'), ('views_user_permission_info', '查看人员权限详细信息')),
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
