# Generated by Django 2.2.1 on 2019-06-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torch', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('url', 'per_method')},
        ),
    ]
